#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII

bspc config border_width         3
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a kitty desktop='^1'
bspc rule -a waterfox-g4 desktop='^2'
bspc rule -a waterfox-classic desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#D5625E"
bspc config normal_border_color         "#2B2F38"
bspc config active_border_color         "#7D3D3D"
bspc config border_radius 15
#
# Autostart
#
# Kill All Applications
pkill picom dunst redshift ksuperkey mpd
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh --blocks &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Night Light
redshift
# Enable super key support
ksuperkey -e 'Super_L=Alt_L|F1' -t 100 &
ksuperkey -e 'Super_R=Alt_L|F1' -t 100 &
# Wallpaper
bash ~/setbkg &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom -b &

# Cursor
xsetroot -cursor_name left_ptr &

# Xfce4 Power Manager
xfce4-power-manager &

# MPD (Music manager and player)
mpd &


